### Reset the database
POST http://localhost:8080/admin/reset

### Test create user (should return 201)
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "saul@bettercall.com"
}

### Test create chirp (should return 201)
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "If you're committed enough, you can make any story work.",
  "user_id": "7e6ae492-3b78-4ce6-bc5a-e772f0941acb"
}

### Create another chirp (should return 201)
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "I once told a woman I was Kevin Costner, and it worked because I believed it.",
  "user_id": "7e6ae492-3b78-4ce6-bc5a-e772f0941acb"
}

### Test get chirp by ID (should return 200)
GET http://localhost:8080/api/chirps/${chirpID}
Content-Type: application/json

{
  "id": "ce1567ac-58bb-49b6-bb00-2aee90fd0c31"
}